In [13]:
import pandas as pd
df=pd.read_excel("student.xls")
df.head()

SEM 1  SEM 2  SEM 3  SEM 4  SEM 5
0   6.60   7.60   6.90   7.22   7.08
1   7.77   7.22   7.00   7.90   7.47
2   6.90   6.00   7.12   7.54   6.89
3   5.50   6.60   6.70   6.50   6.33
4   7.20   6.00   7.21   7.70   7.03

In [14]:
def convert(grade):
    if grade>=8.0:
        return 'excellent'
    elif grade >= 6.0:
        return 'average'
    else:
        return 'improvement'
    
x = df[['SEM 1','SEM 2','SEM 3','SEM 4']]
y=df['SEM 5']
y =y.apply(convert)

#print(x,y)

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.30, random_state=42)

In [44]:
from sklearn.ensemble import RandomForestClassifier
rfr = RandomForestClassifier(n_estimators=10,bootstrap=True)
rfr.fit(x_train,y_train)
y_pred = rfr.predict(x_test)

In [45]:
from sklearn import metrics
print('Accuracy Score:', metrics.accuracy_score(y_test, y_pred))

Accuracy Score: 0.9736842105263158


In [46]:
comparison = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
print(comparison.head(20))  # show first 20 comparisons

          Actual    Predicted
288  improvement  improvement
283  improvement  improvement
327  improvement  improvement
145    excellent    excellent
55       average      average
93       average      average
341  improvement  improvement
82       average      average
366  improvement  improvement
148    excellent    excellent
358  improvement  improvement
209    excellent    excellent
33     excellent    excellent
90       average      average
367  improvement  improvement
314  improvement  improvement
334  improvement  improvement
113    excellent    excellent
320  improvement  improvement
108      average      average


In [47]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[48  1  0]
 [ 1 28  0]
 [ 1  0 35]]


In [48]:
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred, target_names=iris.target_names)
print(cr)

              precision    recall  f1-score   support

      setosa       0.96      0.98      0.97        49
  versicolor       0.97      0.97      0.97        29
   virginica       1.00      0.97      0.99        36

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [54]:
print("pridicted value is")
print(rfr.predict([[1.5,8.4,2.3,8.2]]))

pridicted value is
['excellent']


In [55]:
print(rfr.feature_importances_)

[0.13452755 0.29853896 0.15733039 0.4096031 ]


In [57]:
# Pick one sample
sample = x_test.to_numpy()

# Loop through each tree and print prediction
for i, tree in enumerate(rfr.estimators_):
    pred = tree.predict(sample)[0]
    print(f"Tree {i+1} prediction: {pred}")

# Final Random Forest prediction
print("Random Forest final prediction:", rfr.predict(sample)[0])


Tree 1 prediction: 2.0
Tree 2 prediction: 2.0
Tree 3 prediction: 2.0
Tree 4 prediction: 2.0
Tree 5 prediction: 2.0
Tree 6 prediction: 2.0
Tree 7 prediction: 2.0
Tree 8 prediction: 2.0
Tree 9 prediction: 2.0
Tree 10 prediction: 2.0
Random Forest final prediction: improvement
